name: "✅ Presenta tu solución al reto"
description: "Incluye toda la información necesaria sobre tu solución"
title: "[Solución]: <inserta-aqui-tu-nick-o-nombre>"
labels: ["solución"]
body:
  - type: markdown
    attributes:
      value: "## Pre-requisitos"
  - type: checkboxes
    id: pre-requisitos
    attributes:
      label: Señala los requisitos cumplidos
      description: |
        Asegúrate de cumplir estos requisitos antes de presentar tu solución
      options:
        - label: He subido el proyecto a un repositorio (GitHub, GitLab, etc.)
          required: true
        - label: Mi solución resuelve el problema planteado
          required: true
  - type: markdown
    attributes:
      value: "## Información de la Solución"
  - type: input
    id: nombre-reto
    attributes:
      label: Nombre del Reto
      placeholder: "Ejemplo: Reto de Optimización"
    validations:
      required: true
  - type: input
    id: nombre-equipo
    attributes:
      label: Escribe tu nombre o el del equipo
      placeholder: "Ejemplo: Team Awesome"
    validations:
      required: true
  - type: input
    id: nombre-proyecto
    attributes:
      label: Nombre del Proyecto
      placeholder: "Ejemplo: Mi increíble solución"
    validations:
      required: true
  - type: textarea
    id: descripcion-proyecto
    attributes:
      label: Descripción del Proyecto
      description: Breve descripción de lo que hace tu proyecto y cómo resuelve el reto
      placeholder: "Describa cómo su solución aborda el reto y sus funcionalidades..."
    validations:
      required: true
  - type: input
    id: repositorio-codigo
    attributes:
      label: Repositorio de Código
      description: Enlace al repositorio del proyecto (GitHub, GitLab, etc.)
      placeholder: "Ejemplo: https://github.com/tu-proyecto"
    validations:
      required: true
  - type: input
    id: demostracion-vivo
    attributes:
      label: Proyecto desplegado (opcional)
      description: Enlace a la demostración del proyecto, si aplica
      placeholder: "Ejemplo: https://tu-demostracion.com"
  - type: markdown
    attributes:
      value: "## Documentación"
  - type: textarea
    id: instrucciones-configuracion
    attributes:
      label: Instrucciones de Configuración
      description: Pasos para configurar y ejecutar el proyecto
      placeholder: "Por ejemplo: Clonar el repositorio y ejecutar 'npm install'."
  - type: markdown
    attributes:
      value: "## Criterios de Calificación"
  - type: markdown
    attributes:
      value: |
        La calificación se realizará en base a los siguientes criterios:
        - Calidad del código: Claridad y organización del código.
        - Solución del problema: Eficacia de la solución propuesta para el reto.
        - Cumplimiento de funcionalidades: Todas las funcionalidades requeridas están implementadas.
        - Entrega a tiempo: Se respetó el plazo de entrega establecido.
        - Rendimiento: La aplicación funciona de manera eficiente.
